#ifndef __task_queue_hpp__
#define __task_queue_hpp__



#include "observed.hpp"
#include "queue.hpp"
#include "useful_methods.hpp"


#if __MWERKS__
#pragma export on
#endif


class task_queue;


typedef __u64				task_id_t;
typedef __u32				task_type_t;


typedef __s32	(*task_comparison_proc)( const struct task *in_lhs, const struct task *in_rhs );
typedef void	(*task_completion_proc)( struct task_completion_params *io_task_completion_params );
typedef void	(*task_handler_proc)( struct task_handler_params *io_task_handler_params );


struct task {
	void				   *data;
	__u32					data_size;
	task_handler_proc		handler;
	void				   *handler_context;
	task_type_t				task_type;
};


// The task_queue allocates a new task_observer_data with each notification.  It is the
// responsibility of the observer_callback() to delete the passed task_observer_data.
struct task_observer_data {
	task_observer_data( task_queue *in_task_queue, task_id_t in_task_id ) {
		memset( this, 0, sizeof(task_observer_data) );

		task_queue = in_task_queue;
		task_id = in_task_id;
	}
   ~task_observer_data() { if ( description ) free( const_cast<char *>(description) ); }

	const char			   *description;
	double					percent_done;
	__s32					priority;
	task_id_t				task_id;
	task_queue			   *task_queue;
	task_type_t				task_type;
};


/*
	A task_completion_proc is called when a task completes.  The passed
	io_task_completion_info parameter contains the following information:
	
	in_context:			The completion proc context pointer passed to add_task().
	in_err:				The result code returned by the task_handler_proc.
	io_result:			The result data generated by the task if any.  If non-nil on
						return, the task handler will delete[] io_result.
	in_result_size:		The size in bytes of the data pointed to by in_result.
	in_task_id:			The task_id returned by add_task().
*/
struct task_completion_params {
	void				   *in_context;
	err_t					in_err;
	void				   *io_result;
	__u32					in_result_size;
	task_id_t				in_task_id;
};


/*
	A task_handler_proc is called when a task that has been queued is actually scheduled.  The
	passed io_task_handler_info parameter contes the following information:

	NOTE:  The first parameter for in_callback_should_abort and in_callback_progress
		   is this structure (seethe task_handler_report_progress macro below)
	
	in_callback_should_abort:	A function that long-running tasks should call periodically to see
								if a task should be aborted.  The handler_should_abort() macro
								wraps the relevant member variables and may be more convenient to
								use.  A task is not required to abort a task if it has been
								notified that it should do so, however if the handler does choose
								to abort it can set out_err to err_task_aborted_no_completion to
								indicate that the scheduler should *not* call the task's completion
								proc.  The error err_task_aborted is available to let a completion
								proc know that the task was explicitly aborted, although its use
								is not required.
	in_callback_progress:		A function that long-running tasks should call periodically to
								allow UI's to update progress meters.  The
								handler_report_progress() macro may be more convenient to use.
	in_callbacks_context:		A context pointer which must be supplied to all of the callbacks.
	in_context:					The task handler context pointer passed to the add_task() call.
	in_data:					The data for the task to operate on (can be nil).
	in_data_size:				The size in bytes of the data pointed to by in_data.
	in_task_type:				An identifier which uniquely identifies the type of task.

	in_opaque_data:				A pointer reserved for use by the task_queue.  Do not modify.
	
	out_err:					On return, the result code which should be passed to the
								completion proc.
	out_data:					On return, the data (can be nil) which should be returned to the
								completion proc.
	out_data_size:				The size in bytes of the data pointed to by out_data.
*/
struct task_handler_params {
	task_handler_params(
		void *in_task_queue,
		void *in_task,
		v_proc_pv_d_cpc in_progress_callback,
		b_proc_pv in_should_abort_callback
	) :
		in_callbacks_context( in_task_queue ),
		in_opaque_data( in_task ),
		in_callback_progress( in_progress_callback ),
		in_callback_should_abort( in_should_abort_callback )
	{
		in_context = nil;
		in_data = nil;
		in_data_size = 0;
		in_task_type = 0;

		out_err = 0;
		out_data = nil;
		out_data_size = 0;
	}

	b_proc_pv const			in_callback_should_abort;
	v_proc_pv_d_cpc	const	in_callback_progress;
	void * const			in_callbacks_context;
	const void * const		in_opaque_data;
	
	void				   *in_context;
	void				   *in_data;
	__u32					in_data_size;
	task_type_t				in_task_type;
	
	err_t					out_err;
	void				   *out_data;
	__u32					out_data_size;
};

// passing nil for in_description means leave the current description alone
// passing a negative value for in_percent_done indicates that an indeterminate progress indicator
// should be used.
#define task_handler_report_progress( io_task_handler_params, in_percent_done, in_description )	\
	io_task_handler_params->in_callback_progress( io_task_handler_params, double(in_percent_done), in_description )

#define task_handler_should_abort( io_task_handler_params )										\
	io_task_handler_params->in_callback_should_abort( io_task_handler_params )


enum add_task_flags {
	/*	k_add_piggyback causes add_task() to scan the task queue prior to insertion for the
		presence of a task that has the same type as the task being added.  If a task of the same
		type is found, then the new task is not inserted (in other words, the caller believes the
		completion of the task on the queue will serve as completion of the task to be added).
		Note that if a task of a higher priority is being inserted the priority of the task on
		the queue will be upgraded.
	*/
	k_add_piggyback							=		0x1	,	// piggyback on queued tasks only
	k_add_piggyback_scheduled				=		0x2 ,	// piggyback on scheduled tasks only
};


/*
	Parameter block for add_task():

	in_completion:				The method that is called when the task completes
								(can be nil).
	in_completion_context:		The context for the completion proc.
	in_data:					Data which is passed to the handler (can be nil).
	in_data_size:				The size in bytes of the data pointed to by in_data.
	in_flags:					Any of the add_task_flags constants or 0.
	in_handler:					The method that is called when the task is scheduled
								(must not be nil).
	in_handler_context:			The context for the handler proc.
	in_priority:				The priority of the task to add.
	in_task_comparison_proc:	When the k_piggyback* flag(s) are passed, a task is
								considered equal to another task found on the queue
								if the task_type is equal to in_task_type.  In some
								instances this may not be a sufficient comparison.
								If in_task_comparison_proc is non-nil *and* the
								task_type of a task on the queue is equal to
								in_task_type, then the comparison proc will be called.
								The tasks are considered equal if the comparison proc
								returns zero (compare to strcmp() return semantics).
	in_task_description:		An optional UTF8 string description of the task.
	in_task_type:				An id that uniquely identifies the type of task that
								is being added.
	
*/
struct add_task_params {
	add_task_params() { memset( this, 0, sizeof(add_task_params) ); }

	task_completion_proc	in_completion;
	void				   *in_completion_context;
	void				   *in_data;
	__u32					in_data_size;
	__u32					in_flags;
	task_handler_proc		in_handler;
	void				   *in_handler_context;
	__s32					in_priority;
	task_comparison_proc	in_task_comparison_proc;
	const char			   *in_task_description;
	task_type_t				in_task_type;
};


enum task_queue_observer_events {
	k_task_added			=		'tqta'	,
	k_task_completed		=		'tqcm'	,
	k_task_progress			=		'tqpr'	,
	k_task_removed			=		'tqrm'	,
	k_task_requeued			=		'treq'	,
	k_task_scheduled		=		'tqsc'	,
	k_task_thread_entered	=		'tqte'	,
	k_task_thread_exited	=		'tqtx'	,
};


#if 0
#pragma mark task_queue
#endif


class task_queue : public observed {

public:

	task_queue();
	virtual ~task_queue();
			
	/*	add_task() adds a task to the task queue and returns an id which identifies the task.
		In the event that in_params.in_flags specifies k_add_piggyback but does not specify
		k_add_multiple_notifications, add_task will return 0. */
	task_id_t add_task( add_task_params &in_params );

	/*	remove_task() removes an unscheduled task (or tasks) from the task queue.
	
		in_task_id:						If 0, all ids will match, otherwise only a specific task
										is matched.
		in_task_type:					If 0, all types will match, otherwise only a specific type
										is matched.
		in_send_abort_notification:		If true, removed tasks will have their completion procs
										called with an error of err_task_aborted.
		
		Note that calling remove_task( 0, 0, X ) will result in all tasks being removed. */
	void remove_task( task_id_t in_task_id, task_type_t in_task_type = 0, bool in_send_abort_notification = true );

	/*	reorder_task() allows you to move a queued task to another position in the task queue,
		either immediately after the task with id matching in_order_after_task_id, or to the
		head of the list if in_order_after_task_id is zero or not found on the pending task queue.
	*/
	void reorder_task( task_id_t in_task_id, task_id_t in_order_after_task_id = 0 );

	/*	run() reenables a task queue that has been shut down.  A newly created task queue is
		enabled by default so this call is only necessary if you have called shutdown() and
		wish to restart the queue. */
	void run();

	/*	shutdown() causes the immediate removal of all tasks in the task queue, shuts down any
		threads blocked in remove() and waits for the exit of all other handler threads (any thread
		handler checking handler_should_abort() will receive true at this point and should abort).
		Any add_task() calls made after shutdown() will raise an err_task_queue_shutdown exception.
		The queue may be restarted by a call to run().
		
		By default, the completion routines for queued tasks will be called with an error of
		err_task_aborted.  Setting in_send_abort_notifications to false will suppress this
		behavior. */
	void shutdown( bool in_send_abort_notifications = true );

	/*	Locking suspends any operations to the task queue.  Tasks that are currently being handled
		will complete, but pending tasks, additions, and removals will block until unlock() is
		called. */
//	void lock() { m_task_queue.lock(); }
//	void unlock() { m_task_queue.unlock(); }

	/*	become_active_handler_thread() converts the calling thread to a task handler.  This call
		will succeed even if the number of handler threads is already equal to
		m_max_handler_threads.
		
		The in_dont_join_this_thread_on_shutdown flag determines whether or not shutdown()
		will wait (via pthread_join()) for the thread calling become_active_handler_thread()
		to exit before exiting.  If the task_queue is going to be destroyed from a thread
		other than the one calling become_active_handler_thread(), set the
		in_dont_join_this_thread_on_shutdown flag to false. */
	void become_active_handler_thread( bool in_dont_join_this_thread_on_shutdown = true );
	
// methods that return information about the queue:

	/*	Returns the current number of task handler threads (some or all may be blocked). */
	__u32 current_task_handler_threads();

	/*	Returns true if the queue is shutdown. */
	bool is_shutdown();

	/*	Returns the number of task handler threads that the queue is permitted to create. */
	__s32 max_concurrent_task_handler_threads();
	
	/*	Returns the number of seconds an idle handler thread will block waiting for a task before
		exiting. */
	__u32 seconds_before_idle_task_handler_exits();

// methods that change queue behavior:

	/*	set_max_concurrent_task_handler_threads() sets the maximum number of task handler threads
		that can exist simultaneously.  When a task is added via add_task(), one of following
		things will happen:

		1.	If there is at least one handler thread blocked waiting for an insertion, then the
			task will be queued and a handler thread will be unblocked to service it immediately.
			
		2.	If there are no handler threads blocked waiting for insertion, then the handling of the
			task is as follows:
			
			a)	If the maximum concurrent thread limit has not been reached, then a new thread will
				be created and the task will be queued for immediate execution.
				
			b)	If the maximum concurrent thread limit has been reached, then the task will be
				queued and it will be picked up by the next available handler thread.
				
		The default behavior is to not bound the number of handler threads that can be created,
		and can be specified by passing -1 (k_unlimited) to indicate no upper bound on the number
		of handler threads.
		
		Caveats:
		
		It is assumed that calling add_task() means the caller *wants* the task executed.  For this
		reason, explicitly setting the maximum concurrent thread limit to zero indicates that
		add_task() should immediately execute the task and return upon completion. */
	void set_max_concurrent_task_handler_threads( __s32 in_max_handlers );

	/*	set_seconds_before_idle_task_handler_exits() sets the number of seconds an idle task
		handler thread will block waiting for a task to be inserted before exiting.  The default
		is ten minutes. */
	void set_seconds_before_idle_task_handler_exits( __u32 in_seconds );

protected:

	struct task_completion_notifier {
		bool										aborted;
		task_completion_proc						completion;
		void									   *context;
		task_id_t									task_id;
	};

	struct notify_task : public task {
		priority_queue<task_completion_notifier>	notify_list;			// a list of notifications to be made when the task completes
	};
	
	atomic_queue<void>								m_active_handler_no_join_threads;
	atomic_queue<void>								m_active_handler_threads;
	__u32											m_idle_task_handler_timeout;
	__s32											m_max_handler_threads;
	mutex											m_mutex_create_task;
	mutex											m_mutex_shutdown;
	mutex											m_mutex_shutting_down;
	task_id_t										m_next_task_id;
	priority_queue<notify_task>						m_scheduled_tasks;		// operations need to be done under m_task_queue mutex lock
	atomic_priority_cond_wait_queue<notify_task>	m_task_queue;

	__u32											m_shutdown			:	1;

	void thread_loop();
	void handle_task( notify_task *in_task );

	virtual void *copy_data( __u32 in_event, const void *in_data, __u32 in_data_size );

	static void create_task_thread( task_queue *in_queue );
	static void *task_thread_entry( task_queue *in_queue );
	static bool should_abort_callback( task_handler_params *in_params );
	static void progress_callback( task_handler_params *in_params, double in_percent_done, const char *in_description );
};


#if __MWERKS__
#pragma export reset
#endif



#endif // __task_queue_hpp__
